QLKyTucXa/Controllers/HD_PhongController.cs
using Model.EF;
using QLKyTucXa.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLKyTucXa.Controllers
{
    public class HD_PhongController : BaseController
    {
        private QLKyTucXaDbContext db = new QLKyTucXaDbContext();
        // GET: HD_Phong
        public ActionResult XemHoaDon()
        {
            int uid = Convert.ToInt32(Session["idphong"]);
            var join = (
                from phong in db.PHONGs
                join hoadon_phong in db.HOADON_PHONG on phong.ID_PHONG equals hoadon_phong.ID_PHONG into tableA
                from tA in tableA.DefaultIfEmpty()
                where (phong.TRANGTHAI == true && phong.ID_PHONG == uid)
                orderby (tA.NAM) descending
                select new ViewModel_HD()
                {
                    MAPHONG = phong.MAPHONG,
                    MADAYPHONG = phong.DAYPHONG.MADAYPHONG,
                    NAM = tA.NAM,
                    KY = tA.KY,
                    DONGIA = phong.DONGIA,
                    THANHTIEN = phong.DONGIA * 6,
                    TRANGTHAI = tA.TRANGTHAI
                });
            return View(join);
        }
    }
}

QLKyTucXa/Controllers/HOTROesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model.EF;

namespace QLKyTucXa.Controllers
{
    public class HOTROesController : BaseController
    {
        private QLKyTucXaDbContext db = new QLKyTucXaDbContext();

        // GET: HOTROes
        public ActionResult Index()
        {
            int idphong = Convert.ToInt32(Session["idphong"]);
            var hOTROes = db.HOTROes.Where(p => p.ID_PHONG == idphong).Include(h => h.PHONG);
            return View(hOTROes.ToList());
        }

        // GET: HOTROes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HOTRO hOTRO = db.HOTROes.Find(id);
            if (hOTRO == null)
            {
                return HttpNotFound();
            }
            return View(hOTRO);
        }

        // GET: HOTROes/Create
        public ActionResult Create()
        {
            ViewBag.ID_PHONG = new SelectList(db.PHONGs, "ID_PHONG", "MAPHONG");
            return View();
        }

        // POST: HOTROes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_PHIEU,ID_PHONG,NOIDUNG,NGAYGUI,TRANGTHAI")] HOTRO hOTRO)
        {
            if (ModelState.IsValid)
            {
                int idphong = Convert.ToInt32(Session["idphong"]);
                int trangthai = (hOTRO.TRANGTHAI == 0) ? 0 : 1;
                hOTRO.TRANGTHAI = trangthai;
                hOTRO.NGAYGUI = DateTime.Now;
                hOTRO.ID_PHONG = idphong;
                db.HOTROes.Add(hOTRO);
                db.SaveChanges();
                return RedirectToAction("Index");
                //db.HOTROes.Add(hOTRO);
                //db.SaveChanges();
                //return RedirectToAction("Index");
            }

            ViewBag.ID_PHONG = new SelectList(db.PHONGs, "ID_PHONG", "MAPHONG", hOTRO.ID_PHONG);
            return View(hOTRO);
        }

        // GET: HOTROes/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    HOTRO hOTRO = db.HOTROes.Find(id);
        //    if (hOTRO == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.ID_PHONG = new SelectList(db.PHONGs, "ID_PHONG", "MAPHONG", hOTRO.ID_PHONG);
        //    return View(hOTRO);
        //}

        // POST: HOTROes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "ID_PHIEU,ID_PHONG,NOIDUNG,NGAYGUI,TRANGTHAI")] HOTRO hOTRO)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(hOTRO).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.ID_PHONG = new SelectList(db.PHONGs, "ID_PHONG", "MAPHONG", hOTRO.ID_PHONG);
        //    return View(hOTRO);
        //}

        // GET: HOTROes/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    HOTRO hOTRO = db.HOTROes.Find(id);
        //    if (hOTRO == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(hOTRO);
        //}

        // POST: HOTROes/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    HOTRO hOTRO = db.HOTROes.Find(id);
        //    db.HOTROes.Remove(hOTRO);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLKyTucXa/Controllers/UserVMController.cs
using Model.EF;
using QLKyTucXa.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLKyTucXa.Controllers
{
    public class UserVMController : BaseController
    {
        private QLKyTucXaDbContext db = new QLKyTucXaDbContext();
        // GET: UserVM
        public ActionResult Index()
        {
            int uid = Convert.ToInt32(Session["idphong"]);
            var join = (from phong in db.PHONGs
                        join hoadon in db.HOADON_DIENNUOC on phong.ID_PHONG equals hoadon.ID_PHONG into tableA
                        from tA in tableA.DefaultIfEmpty()

                        join dien in db.CONGTODIENs on phong.ID_PHONG equals dien.ID_PHONG into tableB
                        from tB in tableB.Where(x=>x.THANG == tA.THANG && x.NAM == tA.NAM).DefaultIfEmpty()

                        join nuoc in db.CONGTONUOCs on phong.ID_PHONG equals nuoc.ID_PHONG into tableC
                        from tC in tableC.Where(x=>x.THANG == tA.THANG && x.NAM == tA.NAM).DefaultIfEmpty()

                        join dongia in db.DONGIAs on tA.ID_DONGIA equals dongia.ID_DONGIA into tableD
                        from tD in tableD.DefaultIfEmpty()

                        where (phong.TRANGTHAI == true && phong.ID_PHONG == uid)
                        select new ViewModel_HD()
                        {
                            MAPHONG = phong.MAPHONG,
                            MADAYPHONG = phong.DAYPHONG.MADAYPHONG,
                            DIEN_CHISODAU = tB.CHISODAU,
                            DIEN_CHISOCUOI = tB.CHISOCUOI,
                            CHISODIEN = tB.CHISOCUOI - tB.CHISODAU,
                            NUOC_CHISODAU = tC.CHISODAU,
                            NUOC_CHISOCUOI = tC.CHISOCUOI,
                            CHISONUOC = tC.CHISOCUOI - tC.CHISODAU,
                            THANHTIEN_DIEN = (tB.CHISOCUOI - tB.CHISODAU) * tD.DONGIADIEN,
                            THANHTIEN_NUOC = (tC.CHISOCUOI - tC.CHISODAU) * tD.DONGIANUOC,
                            THANHTIEN = (tB.CHISOCUOI - tB.CHISODAU) * tD.DONGIADIEN + (tC.CHISOCUOI - tC.CHISODAU) * tD.DONGIANUOC,
                            THANG = tA.THANG,
                            NAM = tA.NAM

                        }).ToList().Distinct();
            return View(join);

        }

        [HttpGet]
        public ActionResult CreateDIEN_NUOC()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateDIEN_NUOC(ViewModel_HD model)
        {
            int uid = Convert.ToInt32(Session["idphong"]);
            model.THANG = System.DateTime.Now.Month;
            model.NAM = System.DateTime.Now.Year;
            CONGTONUOC nuoc = new CONGTONUOC()
            {
                ID_PHONG = uid,
                THANG = model.THANG,
                NAM = model.NAM,
                TRANGTHAI = 1,
                CHISODAU = model.NUOC_CHISODAU,
                CHISOCUOI = model.NUOC_CHISOCUOI
            };
            db.CONGTONUOCs.Add(nuoc);

            // dien
            CONGTODIEN dien = new CONGTODIEN()
            {
                ID_PHONG = uid,
                THANG = model.THANG,
                NAM = model.NAM,
                TRANGTHAI = 1,
                CHISODAU = model.DIEN_CHISODAU,
                CHISOCUOI = model.DIEN_CHISOCUOI
            };
            db.CONGTODIENs.Add(dien);
            db.SaveChanges();
            return RedirectToAction("Index");
            //return View(model);
        }
    }
}

QLKyTucXa/Controllers/XemNVController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model.EF;

namespace QLKyTucXa.Controllers
{
    public class XemNVController : BaseController
    {
        private QLKyTucXaDbContext db = new QLKyTucXaDbContext();

        // GET: XemNV
        public ActionResult Index()
        {
            int uid = Convert.ToInt32(Session["idphong"]);
            var lICH_SU = db.LICH_SU.Include(l => l.NHANVIEN).Include(l => l.PHONG).Where(x=>x.ID_PHONG == uid);
            return View(lICH_SU.ToList());
        }

    }
}

QLKyTucXa/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hệ thống Quản lý Ký túc xá - @ViewBag.Title</title>
    <!-- Latest compiled and minified CSS
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    -->
    <!-- Optional theme
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    -->
    @*link fontawesome version 4.7*@
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        table, th, td {
            border: 2px solid #ccc;
        }

        table {
            border-collapse: collapse;
        }

        tr:hover {
            background-color: #ddd;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color: #000000;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("HỆ THỐNG QUẢN LÝ KÝ TÚC XÁ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse bg-dark">
                <div class="nav navbar-nav navbar-right">
                    @*<button class="btn btn-primary navbar-btn"><span class="glyphicon glyphicon-user"></span> Hồ sơ</button>*@
                    <button class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-log-in"></span> @Html.ActionLink("Đăng xuất", "LogoutPhong", "LoginPhong")</button>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-inverse" style="background-color: #0094ff;">
        <div class="container">
            <div class="navbar-collapse collapse bg-dark">
                <div class="nav navbar-nav">
                    <button class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-th-list"></span> @Html.ActionLink("Công tơ Điện - Nước", "Index", "CONGTODIENNUOCs")</button>
                    <button class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-th-list"></span> @Html.ActionLink("Xem Hóa Đơn Điện Nước", "Index", "UserVM")</button>
                    <button class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-th-list"></span> @Html.ActionLink("Xem Hóa Đơn Phòng", "XemHoaDon", "HD_Phong")</button>
                    <button class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-th-list"></span> @Html.ActionLink("Xem Nhân Viên", "Index", "XemNV")</button>
                    <button class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-th-list"></span> @Html.ActionLink("Hỗ trợ", "Index", "HOTROes")</button>
                    <button class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-th-list"></span> @Html.ActionLink("Thêm Chỉ Số Điện - Nước", "CreateDIEN_NUOC", "UserVM")</button>
                </div>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year Quản lý Ký Túc Xá - Trung tâm Công nghệ phần mềm (VNPT-IT khu vực 5)</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

@*<!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Hệ thống Quản lý Ký túc xá - @ViewBag.Title</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
    </html>*@

@*<!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - My ASP.NET Application</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
    </html>*@

QLKyTucXa/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Hệ thống quản lý - Ký túc xá</title>
    <meta charset="utf-8" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/Assets/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Assets/css/bootstrap-responsive.min.css" />
    <link rel="stylesheet" href="~/Assets/css/colorpicker.css" />
    <link rel="stylesheet" href="~/Assets/css/datepicker.css" />
    <link rel="stylesheet" href="~/Assets/css/uniform.css" />
    <link rel="stylesheet" href="~/Assets/css/select2.css" />
    <link rel="stylesheet" href="~/Assets/css/maruti-style.css" />
    <link rel="stylesheet" href="~/Assets/css/maruti-media.css" class="skin-color" />
</head>
<body>

    <div id="header">
        <h1>@Html.ActionLink("Hệ thống quản lý - Ký túc xá", "Index", "Home")</h1>
    </div>

    <div class="btn-group rightzero"> <a class="top_message tip-left" title="Manage Files"><i class="icon-file"></i></a> <a class="top_message tip-bottom" title="Manage Users"><i class="icon-user"></i></a> <a class="top_message tip-bottom" title="Manage Comments"><i class="icon-comment"></i><span class="label label-important">5</span></a> <a class="top_message tip-bottom" title="Manage Orders"><i class="icon-shopping-cart"></i></a> </div>

    <div id="user-nav" class="navbar navbar-inverse">
        <ul class="nav">
            <li>@Html.ActionLink("Đăng xuất", "LogoutPhong", "LoginPhong")</li>
        </ul>
    </div>

    @RenderPage("_Sidebar.cshtml")

    <div id="content">
        <div id="content-header">
            <div id="breadcrumb"> <a href="#" title="" class="tip-bottom"><i class="icon-home"></i> @RenderSection("header", required: false)</a></div>
        </div>
        @RenderBody()
    </div>
    <div class="row-fluid">
        <div id="footer" class="span12"> Copyright &copy; @DateTime.Now.Year Quản lý Ký Túc Xá - Trung tâm Công nghệ phần mềm (VNPT-IT khu vực 5)</div>
    </div>
    <script src="~/Assets/js/jquery.min.js"></script>
    <script src="~/Assets/js/jquery.ui.custom.js"></script>
    <script src="~/Assets/js/bootstrap.min.js"></script>
    <script src="~/Assets/js/bootstrap-colorpicker.js"></script>
    <script src="~/Assets/js/bootstrap-datepicker.js"></script>
    <script src="~/Assets/js/jquery.dataTables.min.js"></script>
    <script src="~/Assets/js/jquery.uniform.js"></script>
    <script src="~/Assets/js/select2.min.js"></script>
    <script src="~/Assets/js/maruti.js"></script>
    <script src="~/Assets/js/maruti.form_common.js"></script>
    <script src="~/Assets/js/maruti.tables.js"></script>
</body>
</html>

QLKyTucXa/Views/Shared/_Sidebar.cshtml
<div id="sidebar">
    <a href="#" class="visible-phone"><i class="icon icon-home"></i> Quản lý </a><ul>
    <li><i class="icon icon-th-list"></i> <span>@Html.ActionLink("Công tơ Điện - Nước", "Index", "CONGTODIENNUOCs")</span></li>
    <li><i class="icon icon-th-list"></i> <span>@Html.ActionLink("Xem Hóa Đơn Điện Nước", "Index", "UserVM")</span></li>
    <li><i class="icon icon-th-list"></i> <span>@Html.ActionLink("Xem Hóa Đơn Phòng", "XemHoaDon", "HD_Phong")</span></li>
    <li><i class="icon icon-th-list"></i> <span>@Html.ActionLink("Xem Nhân Viên", "Index", "XemNV")</span></li>
    <li><i class="icon icon-th-list"></i> <span>@Html.ActionLink("Hỗ trợ", "Index", "HOTROes")</span></li>
    <li><i class="icon icon-th-list"></i> <span>@Html.ActionLink("Thêm Chỉ Số Điện - Nước", "CreateDIEN_NUOC", "UserVM")</span></li>
</ul>
</div>