QLKyTucXa/Areas/CanBo/Controllers/CanboController.cs
using Model.EF;
using QLKyTucXa.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLKyTucXa.Areas.CanBo.Controllers
{
    public class CanboController : BaseController
    {
        // GET: CanBo/Canbo
        private QLKyTucXaDbContext db = new QLKyTucXaDbContext();

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult AllCanbo()
        {
            try
            {
                var dscb = (from cb in db.CANBOes.Where(x => x.DAXOA != true)
                            select new
                            {
                                ID_CANBO = cb.ID_CANBO,
                                MACB = cb.MACB,
                                TAIKHOAN = cb.TAIKHOAN,
                                TENCB = cb.TENCB
                            }).ToList();

                return Json(new { code = 200, dscb = dscb }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { code = 500, msg = "Lấy danh sách cán bộ thất bại: " + ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public JsonResult DsCanbo(string tuKhoa, int trang)
        {
            try
            {
                int idcb = Convert.ToInt32(Session["idcb"]);
                var qt = db.CANBOes.SingleOrDefault(x => x.ID_CANBO == idcb).QUANTRI == true ? true : false;
                var dscb = (from cb in db.CANBOes
                            .Where(x => x.DAXOA != true //lay nhung cb chua bi xoa
                                && (
                                x.MACB.ToLower().Contains(tuKhoa) //ho ten co chua tu khoa
                                || x.TAIKHOAN.ToLower().Contains(tuKhoa)//hoac dia chi co chua tu khoa
                                || x.TENCB.ToLower().Contains(tuKhoa)//hoac la magv co chua tu khoa
                                || x.EMAIL.ToLower().Contains(tuKhoa)//email co chua tu khoa
                                || x.SDT.ToLower().Contains(tuKhoa) //hoac la sodienthoai co chua tu khoa
                                )
                            )
                            select new
                            {
                                ID_CANBO = cb.ID_CANBO,
                                MACB = cb.MACB,
                                TAIKHOAN = cb.TAIKHOAN,
                                MATKHAU = cb.MATKHAU,
                                TENCB = cb.TENCB,
                                GIOITINH = cb.GIOITINH,
                                CMND_CCCD = cb.CMND_CCCD,
                                DIACHI = cb.DIACHI,
                                EMAIL = cb.EMAIL,
                                SDT = cb.SDT,
                                //QUANTRI = cb.QUANTRI //true
                            }).ToList();


                var pageSize = 10;

                var soTrang = dscb.Count() % pageSize == 0 ? dscb.Count() / pageSize : dscb.Count() / pageSize + 1;

                var kqht = dscb
                            .Skip((trang - 1) * pageSize)
                             .Take(pageSize)
                             .ToList();
                return Json(new { code = 200, soTrang = soTrang, dscb = kqht, qt = qt, idcb = idcb, msg = "Lấy danh sách cán bộ thành công!" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { code = 500, msg = "Lấy danh sách cán bộ thất bại: " + ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public JsonResult ChiTiet(int id)
        {
            try
            {
                db.Configuration.ProxyCreationEnabled = false;//cấu hình proxy cho database
                var cb = db.CANBOes.SingleOrDefault(x => x.ID_CANBO == id);
                return Json(new { code = 200, cb = cb }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { code = 500, msg = "Lấy thông tin chi tiết của cán bộ thất bại: " + ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult ThemMoi(string maCB, string taiKhoan, string matKhau, string tenCB, bool gioiTinh, string cmndCccd, string diaChi, string email, string sdt) //, bool quanTri
        {
            try
            {
                var chk = db.CANBOes.Where(x => x.TAIKHOAN == taiKhoan).Count() == 0;
                var chk1 = db.CANBOes.Where(x => x.MACB == maCB).Count() == 0;
                if (!chk)
                {
                    return Json(new { code = 300, msg = "Tài khoản cán bộ này đã tồn tại trong hệ thống!" }, JsonRequestBehavior.AllowGet);
                }
                if (!chk1)
                {
                    return Json(new { code = 301, msg = "Mã cán bộ này đã tồn tại trong hệ thống!" }, JsonRequestBehavior.AllowGet);
                }
                var cb = new CANBO();
                var encryptedMd5Pas = Encryptor.MD5Hash(matKhau);

                cb.MACB = maCB;
                cb.TAIKHOAN = taiKhoan;
                cb.MATKHAU = encryptedMd5Pas;
                cb.TENCB = tenCB;
                cb.GIOITINH = gioiTinh;
                cb.CMND_CCCD = cmndCccd;
                cb.DIACHI = diaChi;
                cb.EMAIL = email;
                cb.SDT = sdt;
                cb.QUANTRI = false;
                cb.DAXOA = false;

                db.CANBOes.Add(cb);

                db.SaveChanges();

                return Json(new { code = 200, msg = "Thêm mới cán bộ thành công" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { code = 500, msg = "Thêm mới cán bộ thất bại: " + ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult CapNhat(int id, string diaChi, string email, string sdt) //, string maCB, string taiKhoan, string matKhau, string tenCB, bool gioiTinh, string cmndCccd, bool quanTri
        {
            try
            {
                var cb = db.CANBOes.SingleOrDefault(x => x.ID_CANBO == id);
                //var encryptedMd5Pas = Encryptor.MD5Hash(matKhau);

                //cb.MACB = maCB;
                //cb.TAIKHOAN = taiKhoan;
                //cb.MATKHAU = encryptedMd5Pas;
                //cb.TENCB = tenCB;
                //cb.GIOITINH = gioiTinh;
                //cb.CMND_CCCD = cmndCccd;
                cb.DIACHI = diaChi;
                cb.EMAIL = email;
                cb.SDT = sdt;
                //cb.QUANTRI = false;
                //cb.DAXOA = false;

                db.SaveChanges();

                return Json(new { code = 200, msg = "Cập nhật thông tin cán bộ thành công" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { code = 500, msg = "Cập nhật thông tin cán bộ thất bại: " + ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }


        [HttpPost]
        public JsonResult Xoa(int id)
        {
            try
            {
                var cb = db.CANBOes.SingleOrDefault(x => x.ID_CANBO == id);
                cb.DAXOA = true;
                db.SaveChanges();

                return Json(new { code = 200, msg = "Xóa cán bộ thành công" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { code = 500, msg = "Xóa cán bộ thất bại: " + ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        
        public JsonResult XacNhan(int id)
        {
            try
            {
                var cb = db.CANBOes.SingleOrDefault(x => x.ID_CANBO == id);
                cb.QUANTRI = true;
                db.SaveChanges();
                return Json(new { code = 200, msg = "Thêm quản trị viên thành công!" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { code = 500, msg = "Thêm quản trị viên thất bại: "+ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public JsonResult ListApply()
        {
            try
            {
                var apply = (from cb in db.CANBOes.Where(x => x.QUANTRI != true && x.DAXOA != true)
                          select new
                          {
                              ID_CANBO = cb.ID_CANBO,
                              MACB = cb.MACB,
                              TAIKHOAN = cb.TAIKHOAN,
                              MATKHAU = cb.MATKHAU,
                              TENCB = cb.TENCB,
                              GIOITINH = cb.GIOITINH,
                              CMND_CCCD = cb.CMND_CCCD,
                              DIACHI = cb.DIACHI,
                              EMAIL = cb.EMAIL,
                              SDT = cb.SDT
                          }).ToList();
                return Json(new { code = 200, apply = apply, msg = "Lấy danh sách cán bộ quản lý thành công!" }, JsonRequestBehavior.AllowGet);
            }

            catch (Exception ex)
            {
                return Json(new { code = 500, msg = "Lấy danh sách cán bộ quản lý thất bại: " + ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public JsonResult ChiTietPass(int id)
        {
            try
            {
                db.Configuration.ProxyCreationEnabled = false;//cấu hình proxy cho database
                var cb = db.CANBOes.SingleOrDefault(x => x.ID_CANBO == id);
                return Json(new { code = 200, cb = cb }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

QLKyTucXa/Areas/CanBo/Controllers/LoginController.cs
using Model.DAO;
using QLKyTucXa.Areas.CanBo.Models;
using QLKyTucXa.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLKyTucXa.Areas.CanBo.Controllers
{
    public class LoginController : Controller
    {
        // GET: CanBo/Login
        public ActionResult Index()
        {
            if (Session[CommonConstants.USER_SESSION] != null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        public ActionResult Logout()
        {
            Session[CommonConstants.USER_SESSION] = null;
            return Redirect("/CanBo/Login");
        }
        public ActionResult Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var dao = new CanBoDAO();
                var result = dao.Login(model.TAIKHOAN, Encryptor.MD5Hash(model.MATKHAU));
                if (result == 1)
                {
                    var user = dao.GetById(model.TAIKHOAN);
                    var userSession = new CanBoLogin();
                    userSession.TAIKHOAN = user.TAIKHOAN;
                    userSession.UserID = user.ID_CANBO;
                    Session["idcb"] = user.ID_CANBO;//lay session
                    Session.Add(CommonConstants.USER_SESSION, userSession);
                    return RedirectToAction("Index", "Home");
                }
                else if (result == 0)
                {
                    ModelState.AddModelError("", "Tài khoản không tồn tại!");
                }
                else if (result == -1)
                {
                    ModelState.AddModelError("", "Mật khẩu không đúng!");
                }
                else if (result == -2)
                {
                    ModelState.AddModelError("", "Tài khoản đang bị khóa!");
                }
                else
                {
                    ModelState.AddModelError("", "Đăng nhập không thành công!");
                }
            }
            return View("Index");
        }
    }
}

QLKyTucXa/Controllers/HOTROesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model.EF;

namespace QLKyTucXa.Controllers
{
    public class HOTROesController : BaseController
    {
        private QLKyTucXaDbContext db = new QLKyTucXaDbContext();

        // GET: HOTROes
        public ActionResult Index()
        {
            int idphong = Convert.ToInt32(Session["idphong"]);
            var hOTROes = db.HOTROes.Where(p => p.ID_PHONG == idphong).Include(h => h.PHONG);
            return View(hOTROes.ToList());
        }

        // GET: HOTROes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HOTRO hOTRO = db.HOTROes.Find(id);
            if (hOTRO == null)
            {
                return HttpNotFound();
            }
            return View(hOTRO);
        }

        // GET: HOTROes/Create
        public ActionResult Create()
        {
            ViewBag.ID_PHONG = new SelectList(db.PHONGs, "ID_PHONG", "MAPHONG");
            return View();
        }

        // POST: HOTROes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_PHIEU,ID_PHONG,NOIDUNG,NGAYGUI,TRANGTHAI")] HOTRO hOTRO)
        {
            if (ModelState.IsValid)
            {
                int idphong = Convert.ToInt32(Session["idphong"]);
                int trangthai = (hOTRO.TRANGTHAI == 0) ? 0 : 1;
                hOTRO.TRANGTHAI = trangthai;
                hOTRO.NGAYGUI = DateTime.Now;
                hOTRO.ID_PHONG = idphong;
                db.HOTROes.Add(hOTRO);
                db.SaveChanges();
                return RedirectToAction("Index");
                //db.HOTROes.Add(hOTRO);
                //db.SaveChanges();
                //return RedirectToAction("Index");
            }

            ViewBag.ID_PHONG = new SelectList(db.PHONGs, "ID_PHONG", "MAPHONG", hOTRO.ID_PHONG);
            return View(hOTRO);
        }

        // GET: HOTROes/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    HOTRO hOTRO = db.HOTROes.Find(id);
        //    if (hOTRO == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.ID_PHONG = new SelectList(db.PHONGs, "ID_PHONG", "MAPHONG", hOTRO.ID_PHONG);
        //    return View(hOTRO);
        //}

        // POST: HOTROes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "ID_PHIEU,ID_PHONG,NOIDUNG,NGAYGUI,TRANGTHAI")] HOTRO hOTRO)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(hOTRO).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.ID_PHONG = new SelectList(db.PHONGs, "ID_PHONG", "MAPHONG", hOTRO.ID_PHONG);
        //    return View(hOTRO);
        //}

        // GET: HOTROes/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    HOTRO hOTRO = db.HOTROes.Find(id);
        //    if (hOTRO == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(hOTRO);
        //}

        // POST: HOTROes/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    HOTRO hOTRO = db.HOTROes.Find(id);
        //    db.HOTROes.Remove(hOTRO);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLKyTucXa/Areas/CanBo/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hệ thống Quản lý Ký túc xá - @ViewBag.Title</title>
    <link href="~/Public/Public/css/all.min.css" rel="stylesheet" />
    <link href="~/Public/Public/css/LayoutAdmin.css" rel="stylesheet" />>
    <!-- Latest compiled and minified CSS
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    -->
    <!-- Optional theme
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    -->
    @*link fontawesome version 4.7*@
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        table, th, td {
            border: 2px solid #ccc;
        }

        table {
            border-collapse: collapse;
        }

        tr:hover {
            background-color: #ddd;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color: #000000;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("HỆ THỐNG QUẢN LÝ KÝ TÚC XÁ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse bg-dark">
                <div class="nav navbar-nav navbar-right">
                    @*<button class="btn btn-primary navbar-btn"><span class="glyphicon glyphicon-user"></span> Hồ sơ</button>*@
                    <button class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-log-in"></span> @Html.ActionLink("Đăng xuất", "Logout", "Login")</button>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-inverse" style="background-color: #0094ff;">
        <div class="container">
            <div class="navbar-collapse collapse bg-dark">
                <div class="nav navbar-nav">
                    <button class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-th-list"></span> @Html.ActionLink("Cán bộ", "Index", "Canbo")</button>
                    <button class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-th-list"></span> @Html.ActionLink("Nhân viên", "Index", "Nhanvien")</button>
                    <button class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-th-list"></span> @Html.ActionLink("Dãy phòng", "Index", "Dayphong")</button>
                    <button class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-th-list"></span> @Html.ActionLink("Phòng", "Index", "Phong")</button>
                    <button class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-th-list"></span> @Html.ActionLink("Tạo hóa đơn điện nước", "Index", "HOADON_DIENNUOC")</button>
                    <button class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-th-list"></span> @Html.ActionLink("Đăng ký phòng cho nhân viên", "Index", "ThemNV")</button>
                    <button class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-th-list"></span> @Html.ActionLink("Hóa đơn phòng", "Index", "HOADON_PHONG")</button>
                    <button class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-th-list"></span> @Html.ActionLink("Công tơ điện nước", "Index", "DIENNUOCs")</button>
                    <button class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-th-list"></span> @Html.ActionLink("Đơn giá", "Index", "Dongia")</button>
                    <button class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-th-list"></span> @Html.ActionLink("Hỗ trợ", "Index", "HOTROes")</button>
                </div>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year Quản lý Ký Túc Xá - Trung tâm Công nghệ phần mềm (VNPT-IT khu vực 5)</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

@*<!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Hệ thống Quản lý Ký túc xá - @ViewBag.Title</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
    </html>*@

QLKyTucXa/Areas/CanBo/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Hệ thống quản lý - Ký túc xá</title>
    <meta charset="utf-8" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/Assets/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Assets/css/bootstrap-responsive.min.css" />
    <link rel="stylesheet" href="~/Assets/css/colorpicker.css" />
    <link rel="stylesheet" href="~/Assets/css/datepicker.css" />
    <link rel="stylesheet" href="~/Assets/css/uniform.css" />
    <link rel="stylesheet" href="~/Assets/css/select2.css" />
    <link rel="stylesheet" href="~/Assets/css/maruti-style.css" />
    <link rel="stylesheet" href="~/Assets/css/maruti-media.css" class="skin-color" />
</head>
<body>

    <div id="header">
        <h1><a href="dashboard.html">Hệ thống quản lý - Ký túc xá</a></h1>
    </div>

    <div class="btn-group rightzero"> <a class="top_message tip-left" title="Manage Files"><i class="icon-file"></i></a> <a class="top_message tip-bottom" title="Manage Users"><i class="icon-user"></i></a> <a class="top_message tip-bottom" title="Manage Comments"><i class="icon-comment"></i><span class="label label-important">5</span></a> <a class="top_message tip-bottom" title="Manage Orders"><i class="icon-shopping-cart"></i></a> </div>

    <div id="user-nav" class="navbar navbar-inverse">
        <ul class="nav">
            <li>@Html.ActionLink("Đăng xuất", "Logout", "Login")</li>
        </ul>
    </div>

    @RenderPage("_Sidebar.cshtml")

    <div id="content">
        <div id="content-header">
            <div id="breadcrumb"> <a href="#" title="" class="tip-bottom"><i class="icon-home"></i> @RenderSection("header", required: false)</a></div>
        </div>
        @RenderBody()
    </div>
    <div class="row-fluid">
        <div id="footer" class="span12"> Copyright &copy; @DateTime.Now.Year Quản lý Ký Túc Xá - Trung tâm Công nghệ phần mềm (VNPT-IT khu vực 5)</div>
    </div>
    <script src="~/Assets/js/jquery.min.js"></script>
    <script src="~/Assets/js/jquery.ui.custom.js"></script>
    <script src="~/Assets/js/bootstrap.min.js"></script>
    <script src="~/Assets/js/bootstrap-colorpicker.js"></script>
    <script src="~/Assets/js/bootstrap-datepicker.js"></script>
    <script src="~/Assets/js/jquery.dataTables.min.js"></script>
    <script src="~/Assets/js/jquery.uniform.js"></script>
    <script src="~/Assets/js/select2.min.js"></script>
    <script src="~/Assets/js/maruti.js"></script>
    <script src="~/Assets/js/maruti.form_common.js"></script>
    <script src="~/Assets/js/maruti.tables.js"></script>
</body>
</html>

QLKyTucXa/Areas/CanBo/Views/Shared/_Sidebar.cshtml
<div id="sidebar">
    <a href="#" class="visible-phone"><i class="icon icon-home"></i> Quản lý </a><ul>
    <li><i class="icon icon-th-list"></i> <span>@Html.ActionLink("Cán bộ", "Index", "Canbo")</span></li>
    <li><i class="icon icon-th-list"></i> <span>@Html.ActionLink("Nhân viên", "Index", "Nhanvien")</span></li>
    <li><i class="icon icon-th-list"></i> <span>@Html.ActionLink("Dãy phòng", "Index", "Dayphong")</span></li>
    <li><i class="icon icon-th-list"></i> <span>@Html.ActionLink("Phòng", "Index", "Phong")</span></li>
    <li><i class="icon icon-th-list"></i> <span>@Html.ActionLink("Tạo hóa đơn điện nước", "Index", "HOADON_DIENNUOC")</span></li>
    <li><i class="icon icon-th-list"></i> <span>@Html.ActionLink("Đăng ký phòng cho nhân viên", "Index", "ThemNV")</span></li>
    <li><i class="icon icon-th-list"></i> <span>@Html.ActionLink("Hóa đơn phòng", "Index", "HOADON_PHONG")</span></li>
    <li><i class="icon icon-th-list"></i> <span>@Html.ActionLink("Công tơ điện nước", "Index", "DIENNUOCs")</span></li>
    <li><i class="icon icon-th-list"></i> <span>@Html.ActionLink("Đơn giá", "Index", "Dongia")</span></li>
    <li><i class="icon icon-th-list"></i> <span>@Html.ActionLink("Hỗ trợ", "Index", "HOTROes")</span></li>
</ul>
</div>